### ISSUE TITLE
服务端传输问题

### ISSUE THREAD

**Issue by jsnjfz** [zyqwst/print-jasper-client#1]
请问老哥客户端用Object en = HttpRequestUtil.request(httpUrl);接收数据的时候服务端的controller里面怎么把JasperPrint对象返回

**Comment by zyqwst** [comment]
请查看服务端代码https://github.com/zyqwst/PrintServer/blob/master/src/com/albert/servlet/PrintServlet.java

**Comment by jsnjfz** [comment]
非常感谢
